/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Presenter.EmployeeMPresenter;
import Presenter.MainMenuPresenter;
import Presenter.MainMenuManagerPresenter;
import Model.Employee;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import View.interfaces.IEmployeeM;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Objects;
import java.math.BigDecimal;

/**
 *
 * @author MSI GF63
 */
public class EmployeeM extends javax.swing.JFrame implements IEmployeeM {
    
    private EmployeeMPresenter presenter;
    private MainMenuPresenter mainMenuPresenter;
    private MainMenuManagerPresenter mainMenuManagerPresenter;
    private boolean isEditing = false; // Flag để biết đang ở chế độ chỉnh sửa hay thêm mới

    /**
     * Creates new form EmployeeM
     */
    public EmployeeM() {
        this((MainMenuPresenter)null);
    }
    
    public EmployeeM(MainMenuPresenter mainMenuPresenter) {
        this.mainMenuPresenter = mainMenuPresenter;
        this.mainMenuManagerPresenter = null;
        initComponents();
        
        presenter = new EmployeeMPresenter(this);
        if (this.mainMenuPresenter != null) {
            presenter.addListener(this.mainMenuPresenter);
            System.out.println("DEBUG (EmployeeM): Đã đăng ký MainMenuPresenter làm listener cho EmployeeMPresenter.");
        } else {
            System.out.println("DEBUG (EmployeeM): MainMenuPresenter là null, không thể đăng ký listener.");
        }

        // Thêm listener cho table selection
        jTable_Employees.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && jTable_Employees.getSelectedRow() != -1) {
                    presenter.onEmployeeSelected();
                }
            }
        });

        // Thêm window listener
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                if (mainMenuPresenter != null) {
                    presenter.removeListener(mainMenuPresenter);
                    System.out.println("DEBUG (EmployeeM): Đã hủy đăng ký MainMenuPresenter khỏi EmployeeMPresenter.");
                }
            }
        });

        // Cấu hình ban đầu
        updateButtonStates(false);
    }
    
    public EmployeeM(MainMenuManagerPresenter mainMenuManagerPresenter) {
        this.mainMenuManagerPresenter = mainMenuManagerPresenter;
        this.mainMenuPresenter = null;
        initComponents();
        
        presenter = new EmployeeMPresenter(this);

        // Thêm listener cho table selection
        jTable_Employees.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && jTable_Employees.getSelectedRow() != -1) {
                    presenter.onEmployeeSelected();
                }
            }
        });

        // Thêm window listener
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                if (mainMenuManagerPresenter != null) {
                    mainMenuManagerPresenter.showMainMenuManager();
                }
            }
        });

        // Cấu hình ban đầu
        updateButtonStates(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel_Top = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdNgayVaoLam = new com.toedter.calendar.JDateChooser();
        txtLuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Employees = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_TopLayout = new javax.swing.GroupLayout(JPanel_Top);
        JPanel_Top.setLayout(JPanel_TopLayout);
        JPanel_TopLayout.setHorizontalGroup(
            JPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_TopLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addGap(231, 231, 231)
                .addGroup(JPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanel_TopLayout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua))
                    .addComponent(txtTimKiem))
                .addGap(18, 18, 18)
                .addGroup(JPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        JPanel_TopLayout.setVerticalGroup(
            JPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(JPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)))
        );

        jLabel1.setText("Mã nhân viên");

        jLabel2.setText("Tên nhân viên");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Số điện thoại");

        jLabel5.setText("Ngày vào làm");

        jLabel6.setText("Lương");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSDT)
                    .addComponent(jdNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(txtLuong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jdNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jdNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTable_Employees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Ngày vào làm", "Số điện thoại", "Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Employees);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Event handlers
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (mainMenuManagerPresenter != null) {
            mainMenuManagerPresenter.showMainMenuManager();
        }
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (validateForm()) {
            Employee employee = getEmployeeFromForm();
            presenter.addEmployee(employee);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (validateForm()) {
            Employee employee = getEmployeeFromForm();
            presenter.updateEmployee(employee);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String maNv = getSelectedMaNv();
        if (maNv != null && !maNv.trim().isEmpty()) {
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa nhân viên này?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                presenter.deleteEmployee(maNv);
            }
        } else {
            showErrorMessage("Vui lòng chọn nhân viên cần xóa!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String query = txtTimKiem.getText().trim();
        presenter.searchEmployees(query);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    // Implementation của interface IEmployeeM
    @Override
    public void displayEmployees(ArrayList<Employee> employees) {
        DefaultTableModel dtm = (DefaultTableModel) jTable_Employees.getModel();
        dtm.setRowCount(0);

        for (Employee employee : employees) {
            Vector<Object> row = new Vector<>();
            row.add(employee.getMaNv());
            row.add(employee.getTenNv());
            row.add(employee.getNgaySinh() != null ? employee.getNgaySinh().toString() : "");
            row.add(employee.getNgayVaoLam() != null ? employee.getNgayVaoLam().toString() : "");
            row.add(employee.getSdt());
            row.add(employee.getLuong());
            dtm.addRow(row);
        }
    }

    @Override
    public void populateEmployeeDetails(Employee employee) {
        txtMaNV.setText(employee.getMaNv());
        txtMaNV.setEditable(false);
        txtTenNV.setText(employee.getTenNv());
        txtSDT.setText(employee.getSdt());
        txtLuong.setText(employee.getLuong() != null ? employee.getLuong().toString() : "");
        
        // Set dates cho JDateChooser
        if (employee.getNgaySinh() != null) {
            Date ngaySinhDate = Date.from(employee.getNgaySinh().atStartOfDay(ZoneId.systemDefault()).toInstant());
            jdNgaySinh.setDate(ngaySinhDate);
        } else {
            jdNgaySinh.setDate(null);
        }
        
        if (employee.getNgayVaoLam() != null) {
            Date ngayVaoLamDate = Date.from(employee.getNgayVaoLam().atStartOfDay(ZoneId.systemDefault()).toInstant());
            jdNgayVaoLam.setDate(ngayVaoLamDate);
        } else {
            jdNgayVaoLam.setDate(null);
        }
        
        isEditing = true;
        updateButtonStates(true);
    }

    @Override
    public void clearForm() {
        txtMaNV.setText("");
        txtMaNV.setEditable(true);
        txtTenNV.setText("");
        txtSDT.setText("");
        txtLuong.setText("");
        jdNgaySinh.setDate(null);
        jdNgayVaoLam.setDate(null);
        isEditing = false;
        updateButtonStates(false);
    }

    @Override
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public String getSelectedMaNv() {
        int selectedRow = jTable_Employees.getSelectedRow();
        if (selectedRow != -1) {
            return (String) jTable_Employees.getValueAt(selectedRow, 0);
        }
        return null;
    }

    @Override
    public Employee getEmployeeFromForm() {
        String maNv = txtMaNV.getText().trim();
        String tenNv = txtTenNV.getText().trim();
        String sdt = txtSDT.getText().trim();
        String luongStr = txtLuong.getText().trim();
        
        // Convert dates
        LocalDate ngaySinh = null;
        LocalDate ngayVaoLam = null;
        
        if (jdNgaySinh.getDate() != null) {
            ngaySinh = jdNgaySinh.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        if (jdNgayVaoLam.getDate() != null) {
            ngayVaoLam = jdNgayVaoLam.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        BigDecimal luong = null;
        if (!luongStr.isEmpty()) {
            try {
                luong = new BigDecimal(luongStr);
            } catch (NumberFormatException e) {
                // Handle invalid number format
            }
        }
        
        return new Employee(maNv, tenNv, ngaySinh, ngayVaoLam, sdt, luong);
    }

    @Override
    public boolean validateForm() {
        if (txtTenNV.getText().trim().isEmpty()) {
            showErrorMessage("Vui lòng nhập tên nhân viên!");
            txtTenNV.requestFocus();
            return false;
        }
        
        if (jdNgayVaoLam.getDate() == null) {
            showErrorMessage("Vui lòng chọn ngày vào làm!");
            jdNgayVaoLam.requestFocus();
            return false;
        }
        
        String luongStr = txtLuong.getText().trim();
        if (!luongStr.isEmpty()) {
            try {
                new BigDecimal(luongStr);
            } catch (NumberFormatException e) {
                showErrorMessage("Lương phải là số!");
                txtLuong.requestFocus();
                return false;
            }
        }
        
        return true;
    }

    @Override
    public void updateButtonStates(boolean isEditing) {
        btnThem.setEnabled(!isEditing);
        btnSua.setEnabled(isEditing);
        btnXoa.setEnabled(isEditing);
    }

    @Override
    public void clearTableSelection() {
        jTable_Employees.clearSelection();
    }

    @Override
    public Date getNgaySinhFromDateChooser() {
        return jdNgaySinh.getDate();
    }

    @Override
    public Date getNgayVaoLamFromDateChooser() {
        return jdNgayVaoLam.getDate();
    }

    @Override
    public void setNgaySinhToDateChooser(Date date) {
        jdNgaySinh.setDate(date);
    }

    @Override
    public void setNgayVaoLamToDateChooser(Date date) {
        jdNgayVaoLam.setDate(date);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_Top;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Employees;
    private com.toedter.calendar.JDateChooser jdNgaySinh;
    private com.toedter.calendar.JDateChooser jdNgayVaoLam;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
